-- MySQL Script generated by MySQL Workbench
-- Fri 04 Dec 2015 22:34:16 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema add_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema add_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `add_db` DEFAULT CHARACTER SET utf8 ;
USE `add_db` ;

-- -----------------------------------------------------
-- Table `add_db`.`Language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `add_db`.`Language` (
  `id_language` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `dialect` VARCHAR(45) NULL,
  PRIMARY KEY (`id_language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `add_db`.`ProblemCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `add_db`.`ProblemCategories` (
  `problem_categories` VARCHAR(45) NOT NULL,
  `id_problem_category` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_problem_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `add_db`.`RawSMSData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `add_db`.`RawSMSData` (
  `idRawSMSData` INT NOT NULL,
  `msg_contents` MEDIUMTEXT NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRawSMSData`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `add_db`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `add_db`.`Report` (
  `idmain` INT NOT NULL AUTO_INCREMENT,
  `lat` FLOAT(10,6) NOT NULL,
  `long` FLOAT(10,6) NOT NULL,
  `location_is_precise` TINYINT(1) NOT NULL,
  `location_prose` MEDIUMTEXT NULL,
  `problem_prose` MEDIUMTEXT NULL,
  `id_language` INT NULL,
  `time_sent` DATETIME NOT NULL,
  `age` INT NULL,
  `gender` VARCHAR(45) NULL,
  `requires_editing` TINYINT(1) NOT NULL,
  `editor_comments` MEDIUMTEXT NULL,
  `problem_category` INT NULL,
  `is_solved` TINYINT(1) NOT NULL,
  `time_updated` DATETIME NOT NULL,
  `sms_id` INT NOT NULL,
  PRIMARY KEY (`idmain`),
  INDEX `fk_main_1_idx` (`id_language` ASC),
  INDEX `fk_report_problem_categories1_idx` (`problem_category` ASC),
  INDEX `fk_Report_RawSMSData1_idx` (`sms_id` ASC),
  CONSTRAINT `fk_main_1`
    FOREIGN KEY (`id_language`)
    REFERENCES `add_db`.`Language` (`id_language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_problem_categories1`
    FOREIGN KEY (`problem_category`)
    REFERENCES `add_db`.`ProblemCategories` (`id_problem_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Report_RawSMSData1`
    FOREIGN KEY (`sms_id`)
    REFERENCES `add_db`.`RawSMSData` (`idRawSMSData`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
